---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
  - 'bootstrap-forms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'

Director:
  environment_type: 'dev'

Injector:
  ChangePasswordForm:
    Class: BootstrapChangePasswordForm
