---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
  - 'bootstrap-forms/*'
  - 'userforms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'

Director:
  environment_type: 'dev'
SiteConfig:
  extensions:
    - CustomSiteConfig
Injector:
  ChangePasswordForm:
    class: BootstrapChangePasswordForm
  MemberLoginForm:
    class: BootstrapLoginForm
DateField:
  default_config:
    showcalendar: true
